default: &default
  appid: <%= Figaro.env.wechat_app_id %>
  secret: <%= Figaro.env.wechat_secret %>
  token:   <%= Figaro.env.wechat_token %>
  skip_verify_ssl: true

production:
  <<: *default

development:
  <<: *default

test:
  <<: *default
